name: AlternativeCoreWars
version: 0.0.1
main: NeiroNetwork\AlternativeCoreWars\Main
api: 4.0.0
src-namespace-prefix: NeiroNetwork\AlternativeCoreWars
depend:
  - TranslationLibrary
  - VoidGenerator
  - NoWorldCorruption
  - ExperimentalFeatures
  - BetterPmmp
  - Capital
  - Shop
  - ShopForm
